import React from 'react';
import { useTranslation } from 'react-i18next';
import './GovernanceHero.scss';

/**
 * Governance Hero Section Component
 * Displays the main hero section with title, description, and illustration
 */
function GovernanceHero() {
  const { t } = useTranslation();

  return (
    <section className="governance-hero d-flex align-items-center justify-content-between">
      <div className="governance-hero__content">
        <h1 className="governance-hero__title">
          {t('governance.heading', 'Syscoin Governance')}
        </h1>

        <div className="governance-hero__description">
          <p>
            Each month a pot of governance funding is generated by the Syscoin blockchain 'superblock'.
          </p>
          <p>
            Any individual or group can submit a proposal to receive some of these funds. SentryNode owners vote on the proposals using voting technology embedded in the Syscoin blockchain (accessible via the Qt wallet or{' '}
            <span className="governance-hero__link">syshub.org</span>).
          </p>
          <p>
            At the end of the monthly voting period funds are distributed to the proposals with the greatest number of positive votes. Successful projects tend to be those that support and advance Syscoin Platform, such as marketing initiatives and application development.
          </p>
          <p>
            Syscoin have implemented a % decline schedule — starting the first month with 1,500,000 SYS and ending on the 24th month with 196,708 SYS.
          </p>
          <p>
            After that period, the superblock starts with 151,767 SYS a month and will decline 5% every year.
          </p>
        </div>
      </div>

      <div className="governance-hero__image">
        <img
          src="/assets/images/masternode.png"
          alt="Syscoin Governance Illustration"
        />
      </div>
    </section>
  );
}

export default GovernanceHero;
