name: PR Agent

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_PROVIDER: gemini
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LLM_MODEL: gemini-1.5-flash
          # Enable summary comments on PRs
          PR_SUMMARIZER: true
          # Optionally enable full reviews/checklists. Set to true if desired.
          PR_REVIEWER: false
          # Optional: model/provider tuning (defaults work fine)
          # GEMINI_API_BASE: ${{ secrets.GEMINI_API_BASE }}
          # LLM_TEMPERATURE: "0.2"


